using System.Reflection;
using System.Text;
using Twig.Domain.Services.Plan;
using Twig.Domain.ValueObjects;
using Twig.Infrastructure.Plan;
using System.Text.Json;

/// <summary>
/// Installed, executable-matched behavioral guidance from the canonical command
/// reference. Only narrative sections are reused: syntax, option names and defaults
/// always come from ConsoleAppFramework's generated declarations.
///
/// Packaging contract (owned by the parent integration): embed docs/commands/index.json
/// and docs/commands/**/*.md under LogicalName Twig.CommandReference/ followed by the
/// relative path (e.g. Twig.CommandReference/context/show.md). No checkout fallback.
/// </summary>
internal static class CommandHelpReference
{
    internal static void ShowIfPresent(string command, TextWriter? output = null)
    {
        output ??= Console.Out;
        using var indexStream = OpenResource("index.json");
        using var index = JsonDocument.Parse(indexStream);
        foreach (var item in index.RootElement.EnumerateArray())
        {
            if (item.GetProperty("command").GetString() != command) continue;
            var path = item.GetProperty("path").GetString()!;
            using var stream = OpenResource(path);
            using var reader = new StreamReader(stream);
            var narrative = ExtractNarrative(reader.ReadToEnd());
            output.WriteLine();
            output.WriteLine($"Behavior and effects (bundled reference: docs/commands/{path}):");
            output.WriteLine(narrative);
            if (command is "proposal validate" or "proposal seed")
                ShowProposalAuthoring(output);
            return;
        }
        // A newly registered command must get a reference before it is shipped.
        // The completeness test detects this rather than substituting generic claims
        // like 'read only' that hide conditional writes or local journal effects.
        output.WriteLine();
        output.WriteLine($"Behavior reference is not bundled for '{command}'.");
    }

    internal static Stream OpenResource(string relativePath)
    {
        var assembly = typeof(CommandHelpReference).Assembly;
        var expected = "Twig.CommandReference/" + relativePath;
        var name = assembly.GetManifestResourceNames().FirstOrDefault(n =>
            n.Replace('\\', '/') == expected);
        return name is null
            ? throw new InvalidOperationException($"Bundled command help resource missing: {expected}")
            : assembly.GetManifestResourceStream(name)!;
    }

    internal static string ExtractNarrative(string markdown)
    {
        using var reader = new StringReader(markdown);
        using var writer = new StringWriter();
        var include = false;
        while (reader.ReadLine() is { } line)
        {
            if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                var heading = line[3..].Trim();
                include = heading is "Behavior" or "Side effects" or "Effects"
                    || heading.StartsWith("Exit codes", StringComparison.Ordinal)
                    || heading.StartsWith("Failure", StringComparison.Ordinal);
            }
            if (include) writer.WriteLine(line);
        }
        return writer.ToString().TrimEnd();
    }
    private static void ShowProposalAuthoring(TextWriter output)
    {
        output.WriteLine();
        output.WriteLine("Authoring a proposal v1 (example generated by the canonical proposal writer):");
        output.WriteLine("Use the active connection's organization and project, not the GitHub repository.");
        output.WriteLine("For an existing local seed, run: twig proposal seed --id -42 -o json");
        output.WriteLine("Replace -42 with its negative alias. Copy descriptor.identity (a GUID string) to stagedIdentity");
        output.WriteLine("and descriptor.fingerprint to expectedFingerprint exactly; do not paste the whole descriptor.");
        output.WriteLine("Choose a unique operation id. The values below are fictional, not a publishable seed.");
        output.WriteLine("Save the complete JSON inside the active workspace as proposal.json:");
        var example = new PlanDefinition
        {
            Version = 1,
            Workspace = new PlanWorkspace { Organization = "example-org", Project = "example-project" },
            Operations = [new PublishSeedOperation
            {
                Id = "publish-seed-1",
                StagedIdentity = StagedIdentity.FromGuid(Guid.Parse("01900000-0000-7000-8000-000000000001")),
                ExpectedFingerprint = "replace-with-descriptor-fingerprint",
            }],
        };
        using var document = JsonDocument.Parse(PlanDocumentWriter.Write(example));
        using var buffer = new MemoryStream();
        using (var writer = new Utf8JsonWriter(buffer, new JsonWriterOptions { Indented = true }))
            document.RootElement.WriteTo(writer);
        output.WriteLine("```json");
        output.WriteLine(Encoding.UTF8.GetString(buffer.GetBuffer(), 0, checked((int)buffer.Length)));
        output.WriteLine("```");
        output.WriteLine("Check the structure: twig proposal validate --file proposal.json -o json");
        output.WriteLine("Validate parses and computes the digest; it makes no ADO calls or journal writes.");
        output.WriteLine("A valid structure does not prove that the seed exists or that its fingerprint is current.");
        output.WriteLine("Preview imports the local journal and presents review/blockers; it does not authorize or apply.");
        output.WriteLine("Apply requires the previewed exact digest and native authorization, then checks live preconditions.");
        output.WriteLine("Do not edit a previewed file; changed intent needs a fresh file and operation id.");
        var version = typeof(CommandHelpReference).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        var revision = version?.Split('+').Last().Split('.').Last();
        var reference = revision is { Length: 40 } && revision.All(char.IsAsciiHexDigit)
            ? revision : "v" + VersionHelper.GetVersion();
        output.WriteLine($"Versioned reference: https://github.com/{CompanionStartup.ResolveRepoSlug()}/blob/{reference}/docs/commands/plans/README.md");
    }
}

