<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <ProjectReference Include="../../src/Twig/Twig.csproj" />
    <ProjectReference Include="../../tests/Twig.TestKit/Twig.TestKit.csproj" />
  </ItemGroup>
</Project>
