using System.Collections.Generic;

namespace Twig.Infrastructure.Tests.Persistence.Transport;

/// <summary>
/// Approval-style baseline for the transport frozen surface.
/// <para>
/// Every entry is <c>FullTypeName::[MP]:MemberSignature</c> where
/// <c>MemberSignature</c> includes the member name AND full parameter
/// types AND return / property type. Overloads and parameter-type
/// changes are therefore visible; a baseline of names only silently
/// accepts them.
/// </para>
/// <para>
/// Update this list only for a deliberate, contract-reviewed change
/// to the transport surface — that's what makes an accidentally-
/// added authority-bearing verb fail conformance under
/// <see cref="TransportNoAuthorityConformanceTests.FrozenSurface_matches_the_expected_baseline"/>.
/// </para>
/// <para>
/// Update procedure: on failure, the test prints the ADDED / REMOVED
/// diff — paste the ADDED lines here for a deliberate widening, or
/// remove the REMOVED lines here for a deliberate narrowing.
/// </para>
/// </summary>
internal static class TransportSurfaceBaseline
{
    public static IReadOnlyList<string> FrozenSurface { get; } = new List<string>
    {
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:AdapterVersion:System.String",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:Capabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:DisplayName:System.String",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:HumanReadable:System.String",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:SupportedRoles:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportAdapterRole>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrCloseReadout::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrLivenessReadout::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrLivenessReadout::P:Presence:Twig.Infrastructure.Persistence.Transport.TransportLivenessPresence",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrLivenessReadout::P:RecordedAt:System.DateTimeOffset",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrPreflightReadout::P:Confirmed:System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrPreflightReadout::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface+ProcessInvocation::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface+ProcessInvocation::P:StdOut:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface::M:CloseAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrCloseReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface::M:ObservePartialCloseRemainingAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrRemainingReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface::M:PreflightCloseAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrPreflightReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface::M:QueryLivenessAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Int32,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrLivenessReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrProcessHostSurface::M:QueryStatusAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Int32,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrStatusReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrRemainingReadout::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrRemainingReadout::P:Summary:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrRemainingSummary",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrStatusReadout::P:Outcome:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrOperationOutcome",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrStatusReadout::P:RecordedAt:System.DateTimeOffset",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrStatusReadout::P:Status:Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrHostStatus",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:AgentTarget:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:HostAttachmentId:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:HostAttachmentIdKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:Pane:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:Tab:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator::P:Workspace:System.String",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.IHerdrHostSurface::M:CloseAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrCloseReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.IHerdrHostSurface::M:ObservePartialCloseRemainingAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrRemainingReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.IHerdrHostSurface::M:PreflightCloseAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrPreflightReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.IHerdrHostSurface::M:QueryLivenessAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Int32,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrLivenessReadout>",
        "Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.IHerdrHostSurface::M:QueryStatusAsync(Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrTargetLocator,System.Int32,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.Adapters.Herdr.HerdrStatusReadout>",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalPresentationSupportRegistry::M:IsSupported(Twig.Infrastructure.Persistence.Transport.RichAdapterId):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalPresentationSupportRegistry::P:RegisteredRichAdapters:System.Collections.Generic.IReadOnlyList<Twig.Infrastructure.Persistence.Transport.RichAdapterId>",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:Content:System.Object",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:Metadata:System.Collections.Generic.IReadOnlyDictionary<System.String,System.String>",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:ProposalId:System.String",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderer::M:RenderAsync(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal,Twig.Infrastructure.Persistence.Transport.Presentation,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.RenderedProposal>",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderer::M:SelectPresentation(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal,Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord):Twig.Infrastructure.Persistence.Transport.Presentation",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalPresentationSupportRegistry::M:IsSupported(Twig.Infrastructure.Persistence.Transport.RichAdapterId):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalPresentationSupportRegistry::P:RegisteredRichAdapters:System.Collections.Generic.IReadOnlyList<Twig.Infrastructure.Persistence.Transport.RichAdapterId>",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalRenderer::M:RenderAsync(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal,Twig.Infrastructure.Persistence.Transport.Presentation,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.RenderedProposal>",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalRenderer::M:SelectPresentation(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal,Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord):Twig.Infrastructure.Persistence.Transport.Presentation",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::M:RenderAsync(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Infrastructure.Persistence.Transport.RichRenderResult>",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::P:Id:Twig.Infrastructure.Persistence.Transport.RichAdapterId",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::P:TimeoutMs:System.Int32",
        "Twig.Infrastructure.Persistence.Transport.ITerminalTextChangeProposalRenderer::M:Render(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal):Twig.Infrastructure.Persistence.Transport.RenderedProposal",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:CloseAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:DescribeAdapter():Twig.Infrastructure.Persistence.Transport.AdapterDescription",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:DetachAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:PartialCloseAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.PartialCloseScope,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:ProbeLivenessAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.TransportProbeOptions,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:RecordIdentity(Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest):Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::M:ReportStatusAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.TransportProbeOptions,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportStatusObservation>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapter::P:Capabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapterRegistry::M:Resolve(System.String):Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.ITransportAdapter>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapterRegistry::P:All:System.Collections.Generic.IReadOnlyList<Twig.Infrastructure.Persistence.Transport.ITransportAdapter>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:CloseAsync(System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:DetachAsync(System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:ReadWithRevisionAsync(System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope>>",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:WriteAsync(Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord,System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:Reason:Twig.Infrastructure.Persistence.Transport.PartialCloseReason",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:ScopeId:System.String",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:ScopeKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.Presentation+RichAdapter::P:AdapterId:Twig.Infrastructure.Persistence.Transport.RichAdapterId",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentCapabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentRecordedAt:System.DateTimeOffset",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentRecordedStatus:Twig.Infrastructure.Persistence.Transport.RecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentSessionKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentTarget:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:TerminalCapabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:TerminalTarget:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:WorktreeFingerprint:System.String",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:WorktreeTarget:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordedStatusExtensions::M:ToWire(Twig.Infrastructure.Persistence.Transport.RecordedStatus):System.String",
        "Twig.Infrastructure.Persistence.Transport.RecordedStatusExtensions::M:TryParse(System.String,out Twig.Infrastructure.Persistence.Transport.RecordedStatus):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:Body:System.Object",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:PresentationKind:Twig.Infrastructure.Persistence.Transport.RenderedProposalKind",
        "Twig.Infrastructure.Persistence.Transport.RichAdapterId::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.RichAdapterId::P:Role:Twig.Infrastructure.Persistence.Transport.TransportAdapterRole",
        "Twig.Infrastructure.Persistence.Transport.RichRenderResult+Refused::P:Reason:System.String",
        "Twig.Infrastructure.Persistence.Transport.RichRenderResult+Rendered::P:Proposal:Twig.Infrastructure.Persistence.Transport.RenderedProposal",
        "Twig.Infrastructure.Persistence.Transport.TerminalTextChangeProposalRenderer::M:Render(Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal):Twig.Infrastructure.Persistence.Transport.RenderedProposal",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:CheckCapabilityName(System.String):Twig.Domain.Common.Result",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:CloseAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:DetachAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:Fresh(System.DateTimeOffset):Twig.Infrastructure.Persistence.Transport.TransportFreshness",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:PartialCloseAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.PartialCloseScope,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:ProbeLivenessAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.TransportProbeOptions,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation>>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:ReportStatusAsync(Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget,Twig.Infrastructure.Persistence.Transport.TransportProbeOptions,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportStatusObservation>>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterRegistry::M:Resolve(System.String):Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.ITransportAdapter>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterRegistry::P:All:System.Collections.Generic.IReadOnlyList<Twig.Infrastructure.Persistence.Transport.ITransportAdapter>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:AdapterContext:System.Collections.Generic.IReadOnlyDictionary<System.String,System.String>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:HostAttachmentId:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:HostAttachmentIdKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:Role:Twig.Infrastructure.Persistence.Transport.TransportAdapterRole",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:AdapterContext:System.Collections.Generic.IReadOnlyDictionary<System.String,System.String>",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:AdapterId:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:HostAttachmentId:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:HostAttachmentIdKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:Role:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:Capabilities:System.Collections.Generic.IReadOnlyList<System.String>",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:RecordedAt:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:RecordedStatus:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:SessionKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:Capabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:RecordedAt:System.DateTimeOffset",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:RecordedStatus:Twig.Infrastructure.Persistence.Transport.RecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:SessionKind:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:ConnectionRef:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Record:Twig.Infrastructure.Persistence.Transport.TransportRecordDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:RecordedAt:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Revision:System.Int64",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Schema:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:State:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Version:System.Int32",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:ConnectionRef:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:Record:Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:RecordedAt:System.DateTimeOffset",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:Revision:System.Int64",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:State:Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelopeState",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Agent:Twig.Infrastructure.Persistence.Transport.TransportAgentPayload",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Terminal:Twig.Infrastructure.Persistence.Transport.TransportTerminalPayload",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Worktree:Twig.Infrastructure.Persistence.Transport.TransportWorktreePayload",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:IsCommonDenominator(System.String):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:ToWire(Twig.Infrastructure.Persistence.Transport.TransportCapability):System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:TryParse(System.String,out Twig.Infrastructure.Persistence.Transport.TransportCapability):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.TransportEnvelopeMapper::M:FromDocument(Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument):Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope>",
        "Twig.Infrastructure.Persistence.Transport.TransportEnvelopeMapper::M:ToDocument(Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope):Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Error:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Freshness:Twig.Infrastructure.Persistence.Transport.TransportFreshness",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Presence:Twig.Infrastructure.Persistence.Transport.TransportLivenessPresence",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:RecordedAt:System.Nullable<System.DateTimeOffset>",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:Attempted:System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:Error:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:ObservedRemaining:Twig.Infrastructure.Persistence.Transport.TransportPartialCloseRemaining",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:Compute(System.DateTimeOffset,System.DateTimeOffset):Twig.Infrastructure.Persistence.Transport.TransportFreshness",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:IsValid(System.Nullable<System.Int32>):System.Boolean",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:ResolveLivenessBudget(Twig.Infrastructure.Persistence.Transport.TransportProbeOptions):System.Int32",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:ResolveStatusBudget(Twig.Infrastructure.Persistence.Transport.TransportProbeOptions):System.Int32",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeOptions::P:TimeoutMs:System.Nullable<System.Int32>",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Agent:Twig.Infrastructure.Persistence.Transport.TransportAgentDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Terminal:Twig.Infrastructure.Persistence.Transport.TransportTerminalDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Worktree:Twig.Infrastructure.Persistence.Transport.TransportWorktreeDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportShapeValidator::M:Validate(Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope):Twig.Domain.Common.Result",
        "Twig.Infrastructure.Persistence.Transport.TransportShapeValidator::M:ValidateRecord(Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord):Twig.Domain.Common.Result",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:Freshness:Twig.Infrastructure.Persistence.Transport.TransportFreshness",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:RecordedAt:System.Nullable<System.DateTimeOffset>",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:Status:Twig.Infrastructure.Persistence.Transport.RecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:TimeoutError:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalDocument::P:Capabilities:System.Collections.Generic.IReadOnlyList<System.String>",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalDocument::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalPayload::P:Capabilities:System.Collections.Generic.IReadOnlySet<Twig.Infrastructure.Persistence.Transport.TransportCapability>",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalPayload::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreeDocument::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreeDocument::P:WorktreeFingerprint:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreePayload::P:Target:Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreePayload::P:WorktreeFingerprint:System.String",
        "Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome::P:WrittenRevision:System.Int64",
        "Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope::P:Envelope:Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope",
        "Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope::P:Revision:System.Int64",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:CloseAsync(System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:DetachAsync(System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:Dispose():System.Void",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:ReadWithRevisionAsync(System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope>>",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:WriteAsync(Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord,System.Int64,System.Threading.CancellationToken):System.Threading.Tasks.Task<Twig.Domain.Common.Result<Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome>>",
    };
}
