using System.Collections.Generic;

namespace Twig.Infrastructure.Tests.Persistence.Transport;

/// <summary>
/// Approval-style baseline for the transport frozen surface.
/// <para>
/// Every entry is <c>FullTypeName::[MP]:MemberName</c>. Update this
/// list only for a deliberate, contract-reviewed change to the
/// transport surface — that's what makes an accidentally-added
/// authority-bearing verb fail conformance under
/// <see cref="TransportNoAuthorityConformanceTests.FrozenSurface_matches_the_expected_baseline"/>.
/// </para>
/// <para>
/// Update procedure: on failure, the test prints the ADDED / REMOVED
/// diff — paste the ADDED lines here for a deliberate widening, or
/// remove the REMOVED lines here for a deliberate narrowing.
/// </para>
/// </summary>
internal static class TransportSurfaceBaseline
{
    public static IReadOnlyList<string> FrozenSurface { get; } = new List<string>
    {
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:AdapterVersion",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:Capabilities",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:DisplayName",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:HumanReadable",
        "Twig.Infrastructure.Persistence.Transport.AdapterDescription::P:SupportedRoles",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalPresentationSupportRegistry::M:IsSupported",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalPresentationSupportRegistry::P:RegisteredRichAdapters",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:Content",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:Metadata",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderProposal::P:ProposalId",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderer::M:RenderAsync",
        "Twig.Infrastructure.Persistence.Transport.ChangeProposalRenderer::M:SelectPresentation",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalPresentationSupportRegistry::M:IsSupported",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalPresentationSupportRegistry::P:RegisteredRichAdapters",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalRenderer::M:RenderAsync",
        "Twig.Infrastructure.Persistence.Transport.IChangeProposalRenderer::M:SelectPresentation",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::M:RenderAsync",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::P:Id",
        "Twig.Infrastructure.Persistence.Transport.IRichChangeProposalRenderer::P:TimeoutMs",
        "Twig.Infrastructure.Persistence.Transport.ITerminalTextChangeProposalRenderer::M:Render",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapterRegistry::M:Resolve",
        "Twig.Infrastructure.Persistence.Transport.ITransportAdapterRegistry::P:All",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:CloseAsync",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:DetachAsync",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:ReadWithRevisionAsync",
        "Twig.Infrastructure.Persistence.Transport.ITransportAttachmentStore::M:WriteAsync",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:Reason",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:ScopeId",
        "Twig.Infrastructure.Persistence.Transport.PartialCloseScope::P:ScopeKind",
        "Twig.Infrastructure.Persistence.Transport.Presentation+RichAdapter::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentCapabilities",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentRecordedAt",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentRecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentSessionKind",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:AgentTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:TerminalCapabilities",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:TerminalTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:WorktreeFingerprint",
        "Twig.Infrastructure.Persistence.Transport.RecordIdentityRequest::P:WorktreeTarget",
        "Twig.Infrastructure.Persistence.Transport.RecordedStatusExtensions::M:ToWire",
        "Twig.Infrastructure.Persistence.Transport.RecordedStatusExtensions::M:TryParse",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:Body",
        "Twig.Infrastructure.Persistence.Transport.RenderedProposal::P:PresentationKind",
        "Twig.Infrastructure.Persistence.Transport.RichAdapterId::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.RichAdapterId::P:Role",
        "Twig.Infrastructure.Persistence.Transport.RichRenderResult+Refused::P:Reason",
        "Twig.Infrastructure.Persistence.Transport.RichRenderResult+Rendered::P:Proposal",
        "Twig.Infrastructure.Persistence.Transport.TerminalTextChangeProposalRenderer::M:Render",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:CheckCapabilityName",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:CloseAsync",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:DetachAsync",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:Fresh",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:PartialCloseAsync",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:ProbeLivenessAsync",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterDispatcher::M:ReportStatusAsync",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterRegistry::M:Resolve",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterRegistry::P:All",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:AdapterContext",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:HostAttachmentId",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:HostAttachmentIdKind",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTarget::P:Role",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:AdapterContext",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:AdapterId",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:HostAttachmentId",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:HostAttachmentIdKind",
        "Twig.Infrastructure.Persistence.Transport.TransportAdapterTargetDocument::P:Role",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:Capabilities",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:RecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:SessionKind",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentDocument::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:Capabilities",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:RecordedStatus",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:SessionKind",
        "Twig.Infrastructure.Persistence.Transport.TransportAgentPayload::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:ConnectionRef",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Record",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Revision",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Schema",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:State",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentDocument::P:Version",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:ConnectionRef",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:Record",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:Revision",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentEnvelope::P:State",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Agent",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Terminal",
        "Twig.Infrastructure.Persistence.Transport.TransportAttachmentRecord::P:Worktree",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:IsCommonDenominator",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:ToWire",
        "Twig.Infrastructure.Persistence.Transport.TransportCapabilityExtensions::M:TryParse",
        "Twig.Infrastructure.Persistence.Transport.TransportEnvelopeMapper::M:FromDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportEnvelopeMapper::M:ToDocument",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Error",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Freshness",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:Presence",
        "Twig.Infrastructure.Persistence.Transport.TransportLivenessObservation::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:Attempted",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:Error",
        "Twig.Infrastructure.Persistence.Transport.TransportPartialCloseOutcome::P:ObservedRemaining",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:Compute",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:IsValid",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:ResolveLivenessBudget",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeBudget::M:ResolveStatusBudget",
        "Twig.Infrastructure.Persistence.Transport.TransportProbeOptions::P:TimeoutMs",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Agent",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Terminal",
        "Twig.Infrastructure.Persistence.Transport.TransportRecordDocument::P:Worktree",
        "Twig.Infrastructure.Persistence.Transport.TransportShapeValidator::M:Validate",
        "Twig.Infrastructure.Persistence.Transport.TransportShapeValidator::M:ValidateRecord",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:Freshness",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:RecordedAt",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:Status",
        "Twig.Infrastructure.Persistence.Transport.TransportStatusObservation::P:TimeoutError",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalDocument::P:Capabilities",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalDocument::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalPayload::P:Capabilities",
        "Twig.Infrastructure.Persistence.Transport.TransportTerminalPayload::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreeDocument::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreeDocument::P:WorktreeFingerprint",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreePayload::P:Target",
        "Twig.Infrastructure.Persistence.Transport.TransportWorktreePayload::P:WorktreeFingerprint",
        "Twig.Infrastructure.Persistence.Transport.TransportWriteOutcome::P:WrittenRevision",
        "Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope::P:Envelope",
        "Twig.Infrastructure.Persistence.Transport.VersionedTransportEnvelope::P:Revision",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:CloseAsync",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:DetachAsync",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:Dispose",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:ReadWithRevisionAsync",
        "Twig.Infrastructure.Persistence.Transport.WorktreeLocalTransportAttachmentStore::M:WriteAsync",
    };
}
